# Using container-based infrastructure
dist: trusty
sudo: false

# 'bash' will define a generic environment without interfering environment
# settings like "CC=gcc"
language: bash

# Only build the master branch
branches:
    only:
        - master

# Caching the downloaded src packages between several builds to save travis-ci
# download time and bandwidth
cache:
    directories:
        - $HOME/src

# Installing needed dependencies
addons:
    apt:
        packages:
            - bison
            - flex
            - libncurses5-dev
            - texinfo
            - help2man
            - g++

# Building crosstool-NG core
install:
    - ./bootstrap
    - ./configure --enable-local
    - make

# Here is the list of all the standard samples tracked
# by the continuous integration system
env:
    - CT_SAMPLE=x86_64-w64-mingw32,arm-none-eabi
    - CT_SAMPLE=x86_64-w64-mingw32,arm-none-linux-gnueabi
    - CT_SAMPLE=x86_64-w64-mingw32,powerpc-none-linux-gnu
    - CT_SAMPLE=x86_64-w64-mingw32,i686-pc-linux-gnu
    - CT_SAMPLE=x86_64-w64-mingw32,x86_64-pc-linux-gnu

# Building the standard samples
script:
    - . ./.travis.sh      # Load the travis environment
    - ct-ng x86_64-w64-mingw32	  # first step build
    - ct-ng_travis_build  # Build first step
    - export PATH="~/x-tools/x86_64-w64-mingw32/bin:$PATH"
    - ct-ng $CT_SAMPLE    # Configure the build
    - ct-ng_travis_build  # Build the sample

# On failure displaying the last lines of the log file
after_failure:
    - tail -n 1000 build.log
